# Generated by Django 5.1.15 on 2026-08-13 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('job_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('work_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='remote', max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('online_assessment', 'Online Assessment'), ('oa_cleared', 'OA Cleared'), ('interview_r1', 'Interview Round 1'), ('interview_r2', 'Interview Round 2'), ('hr_round', 'HR Round'), ('offer', 'Offer Received'), ('rejected', 'Rejected')], db_index=True, default='saved', max_length=32)),
                ('board_order', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('internshala', 'Internshala'), ('naukri', 'Naukri'), ('indeed', 'Indeed'), ('career_page', 'Company Career Page'), ('referral', 'Referral'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('interview_questions', models.TextField(blank=True)),
                ('dsa_questions', models.TextField(blank=True)),
                ('hr_questions', models.TextField(blank=True)),
                ('personal_notes', models.TextField(blank=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('jd_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_match', to='applications.jobapplication')),
            ],
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status'], name='application_user_id_16fc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'deadline'], name='application_user_id_f72b4b_idx'),
        ),
    ]
