# Generated by Django 5.1.15 on 2026-08-15 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('job_role', models.CharField(max_length=200)),
                ('job_location', models.CharField(blank=True, max_length=200)),
                ('package_lpa', models.FloatField(blank=True, help_text='CTC in LPA', null=True)),
                ('min_cgpa', models.FloatField(default=0.0, help_text='Minimum CGPA required')),
                ('allowed_branches', models.JSONField(blank=True, default=list, help_text='List of allowed branches. Empty = all branches.')),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('graduation_year', models.IntegerField(blank=True, help_text='Eligible graduation year. Null = any.', null=True)),
                ('max_backlogs', models.IntegerField(default=0, help_text='Max allowed active backlogs. 0 = no backlogs allowed.')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Placement Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('company_visit', 'Company Visit'), ('registration', 'Registration'), ('aptitude', 'Aptitude Test'), ('interview', 'Interview'), ('result', 'Result'), ('offer', 'Offer Letter')], db_index=True, default='general', max_length=30)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_announcements', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, help_text='Leave blank for global announcements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='placements.placementcompany')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('on_hold', 'On Hold'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_applications', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.placementcompany')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('company', 'student')},
            },
        ),
        migrations.CreateModel(
            name='EligibleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=True)),
                ('override_reason', models.TextField(blank=True, help_text='Reason for manual override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibilities_added', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_eligibilities', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_students', to='placements.placementcompany')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'student')},
            },
        ),
    ]
