# Generated by Django 5.1.15 on 2026-08-13 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('software', 'Software Developer'), ('data', 'Data Analyst'), ('fullstack', 'Full Stack'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=32)),
                ('file', models.FileField(upload_to='resumes/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('strength_score', models.FloatField(blank=True, null=True)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
                'unique_together': {('user', 'title', 'version')},
            },
        ),
    ]
